name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package does this apply to?
      options:
        - "@claudiv/core"
        - "@claudiv/cli"
        - "@claudiv/vite-sdk"
        - "@claudiv/designer"
        - "New package"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the feature you'd like.
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: What problem does this solve? How would you use it?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any workarounds or alternative approaches you've considered.
